### ISSUE TITLE
PagerDutyPage Component stays loading indefinitely 

### ISSUE THREAD

**Issue by alpinweis** [PagerDuty/backstage-plugin-backend#75]
PagerDutyPage fails to load.

I'm seeing 2 errors in the dev tools console in Chrome:

```
entity:1
Failed to load resource: the server responded with a status of 504 ()  

VM228:1 
Uncaught (in promise) SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
```

**Versions**
Backstage Version: 1.28.2
NodeJS Version: 18.20.4

**PagerDuty plugin versions**

@pagerduty/backstage-plugin: 0.14.0
@pagerduty/backstage-plugin-backend: 0.8.0
@pagerduty/backstage-plugin-common: 0.2.0
@pagerduty/backstage-plugin-entity-processor:	0.2.1

**Comment by t1agob** [comment]
Hello @alpinweis! Thanks for reporting this issue. I'll try to replicate it and get back to you ASAP.

**Comment by alpinweis** [comment]
Some more context: there are around 200 services in my Pagerduty account. I use a REST API Token as auth method.
I tried multiple times to load the page but it only succeeded once, after waiting for about 5 minutes.

**Comment by t1agob** [comment]
Thanks for the additional context. This is most likely something related to the number of requests we are making. I'll look into it.

**Comment by t1agob** [comment]
@alpinweis just to confirm, are you using single account configuration?

**Comment by alpinweis** [comment]
> @alpinweis just to confirm, are you using single account configuration?

yes

**Comment by t1agob** [comment]
@alpinweis I've been unable to replicate the issue so far. Here is what I have tried so far:
- Create more than 200 services in my PagerDuty account
  - for 250 services, my PagerDutyPage takes 4s to load all the data. Can be improved but it doesn't take 5mins like you mention above
- I've refactored some code where I was parsing Json in potential unsafe places
  -  please update to version 0.14.1 (frontend plugin) and version 0.8.2 (backend plugin)

Next, I'll try to look into how we're handling HTTP errors codes in the backend because it might be it. Still, it's strange how we are seeing such different behaviours using the same versions of the packages and backstage.

**Can you possibly share which PagerDuty license type you own?** I just want to rule out all options.

**Comment by alpinweis** [comment]
> Can you possibly share which PagerDuty license type you own?

The API at https://api.pagerduty.com/licenses reports the following licenses for me:
- "Customer Service Business (Full User)"
- "Customer Service Business (Stakeholder)"

**Comment by t1agob** [comment]
@alpinweis Can you update to the latest versions I released yesterday and see if the problem persists? 
> 0.14.1 (frontend plugin) and version 0.8.2 (backend plugin)

I've started the work on revisiting how we handle HTTP error codes.

**Comment by alpinweis** [comment]
Thanks @t1agob. Here's the update:
- Upgraded pagerduty plugins to the latest. 
- Run locally `yarn dev`, waited for all components to finish loading from a remote location (Gihub repo).
- Navigated to the PagerDutyPage. It takes 15 sec in average to load the page. Tried multiple times, with 10-15 sec between retries. It loads every time consistently, but takes about 15 sec every time. Normally I'd expect the page to load immediately after that first successful time. Overall, though, it looks like an improvement.

Is the result of fetching all PagerDuty services and building the mapping supposed to be cached somewhere?

**Comment by t1agob** [comment]
Ah...great to hear! This information is not cached at this point in time...but it will be. It's an improvement I had on my notes but not yet added to the backlog. I'll add a feature request for the caching right now and work on it next.

**I'll close this issue now because it's not blocking anymore.** Thanks for reporting it. It's only possible to improve when users provide this type of feedback.
